{
 "title": "Raspberry / Hardware",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rpi_temperature,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "rpi_voltage_core{instance=\"$instance\"}",
     "legendFormat": "VC4 core"
    },
    {
     "expr": "rpi_voltage_sdram_c{instance=\"$instance\"}",
     "legendFormat": "SDRAM Core"
    },
    {
     "expr": "rpi_voltage_sdram_i{instance=\"$instance\"}",
     "legendFormat": "SDRAM I/O"
    },
    {
     "expr": "rpi_voltage_sdram_p{instance=\"$instance\"}",
     "legendFormat": "SDRAM Phy"
    }
   ]
  },
  {
   "title": "Clocks",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rpi_clock_arm{instance=\"$instance\"}",
     "legendFormat": "ARM core(s)"
    },
    {
     "expr": "rpi_clock_core{instance=\"$instance\"}",
     "legendFormat": "GPU core"
    },
    {
     "expr": "rpi_clock_h264{instance=\"$instance\"}",
     "legendFormat": "H.264 block"
    },
    {
     "expr": "rpi_clock_isp{instance=\"$instance\"}",
     "legendFormat": "Image Sensor Pipeline"
    },
    {
     "expr": "rpi_clock_v3d{instance=\"$instance\"}",
     "legendFormat": "3D block"
    },
    {
     "expr": "rpi_clock_uart{instance=\"$instance\"}",
     "legendFormat": "UART"
    },
    {
     "expr": "rpi_clock_pwm{instance=\"$instance\"}",
     "legendFormat": "PWM block"
    },
    {
     "expr": "rpi_clock_emmc{instance=\"$instance\"}",
     "legendFormat": "SD card interface"
    },
    {
     "expr": "rpi_clock_pixel{instance=\"$instance\"}",
     "legendFormat": "Pixel valves"
    },
    {
     "expr": "rpi_clock_vec{instance=\"$instance\"}",
     "legendFormat": "Analogue video encoder"
    },
    {
     "expr": "rpi_clock_hdmi{instance=\"$instance\"}",
     "legendFormat": "HDMI"
    },
    {
     "expr": "rpi_clock_dpi{instance=\"$instance\"}",
     "legendFormat": "Display Parallel Interface"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rpi_temperature{instance=\"$instance\"}",
     "legendFormat": "Core"
    }
   ]
  }
 ]
}